-- ORACLE
CREATE TABLE IG_FOLLOWERS (
    ID INT GENERATED BY DEFAULT AS IDENTITY,
    ACCOUNT_NAME VARCHAR2(30) NOT NULL,
    RECORDED_ON DATE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IG_FOLLOWING (
    ID INT GENERATED BY DEFAULT AS IDENTITY,
    ACCOUNT_NAME VARCHAR2(30) NOT NULL,
    RECORDED_ON DATE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IG_NMF (
    ID INT GENERATED BY DEFAULT AS IDENTITY,
    ACCOUNT_NAME VARCHAR2(30) NOT NULL,
    RECORDED_ON DATE NOT NULL,
    PROTECTED NUMBER(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY(ID)
);

COMMIT;

-- PostgreSQL
create table ig_followers (
  id serial primary key,
  account_name varchar(30) not null,
  recorded_on date not null
);

create table ig_following (
  id serial primary key,
  account_name varchar(30) not null,
  recorded_on date not null
);

create table ig_nmf (
  id serial primary key,
  account_name varchar(30) not null,
  recorded_on date not null,
  is_protected boolean default false
);
