create table
  public.bookmarks (
    id bigint generated by default as identity not null,
    reference character varying not null,
    link character varying not null,
    craeted timestamp without time zone not null default now(),
    constraint bookmarks_pkey primary key (id),
    constraint bookmarks_id_key unique (id),
    constraint bookmarks_link_key unique (link)
  ) tablespace pg_default;